spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/apidb2
    username: root
    password: 1234

  # upload
  # max-request-size 한번에 받아 들일 수 있는 량
  # max-file-size 한파일의 크기가 얼마만큼 넘어갈 수 없도록 제한
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

  file:
    upload:
      path: upload

#시큐리티 설정
logging:
  level:
    org:
      springframework:
        security:
          web=trace:

#32 글자 이상
jwt:
  secret: DadFufN4Oui8Bfv3ScFj6R9fyJ9hD45E6AGFsXgFsRhT4YSdSb